//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

public partial class UserForm {
    
    /// <summary>
    /// lblTitle control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblTitle;
    /// <summary>
    /// hfUserId control.
    /// </summary>
    protected global::System.Web.UI.WebControls.HiddenField hfUserId;
    /// <summary>
    /// txtUserName control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtUserName;
    /// <summary>
    /// txtFirstName control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtFirstName;
    /// <summary>
    /// txtLastName control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtLastName;
    /// <summary>
    /// txtEmail control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtEmail;
    /// <summary>
    /// chkIsActive control.
    /// </summary>
    protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
    /// <summary>
    /// lblMessage control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblMessage;
}
